title: Check web page accessibility
hero_image: images/banner.png
description: Check web page accessibility
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Check web page accessibility
